name: Jalankan Preprocessing Dataset

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan Preprocessing
      run: python preprocessing/automate_Nama-siswa.py

    - name: Commit hasil preprocessing
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add preprocessing/namadataset_preprocessing/
        git commit -m "Update hasil preprocessing otomatis"
        git push
      continue-on-error: true
